name: Deploy netlify site

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: "Deployed site"
      run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
